2020-02-19 00:16:56,652 INFO: Microblog startup [in /home/artem/PycharmProjects/Flask/Мега-Учебник Flask/microblog/app/routes.py:134]
2020-02-25 23:30:30,441 INFO: Microblog startup [in /home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/routes.py:155]
2020-02-25 23:34:38,648 INFO: Microblog startup [in /home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/routes.py:155]
2020-02-25 23:49:37,671 INFO: Microblog startup [in /home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/routes.py:155]
2020-02-26 23:46:28,973 INFO: Microblog startup [in /home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/routes.py:157]
2020-02-26 23:59:05,365 INFO: Microblog startup [in /home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/routes.py:157]
2020-02-26 23:59:09,435 ERROR: Exception on /reset_password_request [GET] [in /home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/routes.py", line 207, in reset_password_request
    title='Reset Password')
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/templates/email/reset_password.html", line 1, in top-level template code
    <p>Уважаемый {{ user.username }},</p>
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2020-02-26 23:59:30,122 ERROR: Exception on /reset_password_request [GET] [in /home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/routes.py", line 207, in reset_password_request
    title='Reset Password')
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/templates/email/reset_password.html", line 1, in top-level template code
    <p>Уважаемый {{ user.username }},</p>
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2020-02-27 00:00:31,159 INFO: Microblog startup [in /home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/routes.py:157]
2020-02-27 00:03:37,300 INFO: Microblog startup [in /home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/routes.py:157]
2020-02-27 00:04:15,671 ERROR: Exception on /reset_password_request [POST] [in /home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/routes.py", line 200, in reset_password_request
    send_password_reset_email(user)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/email.py", line 21, in send_password_reset_email
    user=user, token=token))
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/email.py", line 10, in send_email
    mail.send(msg)
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/artem/PycharmProjects/Flask/flask_project_1/microblog/venv/lib/python3.6/site-packages/flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "/usr/lib/python3.6/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/lib/python3.6/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.6/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials g15sm1845740ljl.10 - gsmtp')
2020-02-27 00:13:31,124 INFO: Microblog startup [in /home/artem/PycharmProjects/Flask/flask_project_1/microblog/app/routes.py:157]
